name: Mirror Dockerhub

on:
  workflow_dispatch:
  schedule:
    - cron: '2 1 * * 0'

jobs:
  mirror:
    name: Mirror
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: alpine
            repo: docker.io
          - image: docker
            repo: docker.io
          - image: nextcloud
            repo: docker.io
          - image: mariadb
            repo: docker.io
          - image: postgres
            repo: docker.io
          - image: redis
            repo: docker.io
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - uses: actions/setup-go@v5
      - uses: imjasonh/setup-crane@v0.4
      - name: Mirror
        run: |
          for tag in $(cat ./images/${{ matrix.image }}); do
            crane copy \
              ${{ matrix.repo }}/${{ matrix.image }}:$tag \
              ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:$tag;
            sleep 60;
          done
